#!/usr/bin/env bash

if [ "$1" == "start" ]; then
    sudo docker-compose start
fi

if [ "$1" == "stop" ]; then
    sudo docker-compose stop
fi

if [ "$1" == "update" ]; then    
    sudo docker-compose pull && sudo docker-compose up -d && sudo docker image prune -f
fi

if [ "$1" == "setup" ]; then
  echo 'Setting system...' \
  && read -p "Input your Infura node URL (ex. https://rinkeby.infura.io/v3/..... ) : " INFURA \
  && read -p "Input your Ethereum private key (except 0x) : " PRIVKEY \
  && sudo apt update -y && sudo apt upgrade -y && sudo apt install curl git cron nano jq vsftpd -y && sudo apt autoremove -y \
  && sudo rm -rf CreditcoinDockerCompose-2.0 && git clone -b release/2.0 --single-branch https://github.com/woosungchoi/CreditcoinDockerCompose-Testnet CreditcoinDockerCompose-2.0 \
  && cd CreditcoinDockerCompose-2.0 \
  && sed -i "s/<IPADDRESS>/"$(curl -s icanhazip.com)"/g" ./Server/docker-compose.yaml \
  && sed -i "s,<ethereum_node_url>,$INFURA,g" ./Server/gatewayConfig.json \
  && sed -i "s,<ethereum_node_url>,$INFURA,g" ./Client/clientConfig.json \
  && sed -i "s,<ethereum_private_key_no_0x>,$PRIVKEY,g" ./Client/clientConfig.json \
  && echo 'Setting timezone to Asia/Seoul...' \
  && sudo timedatectl set-timezone Asia/Seoul \
  && echo 'Installing Docker...' \
  && sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y \
  && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - \
  && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" -y \
  && sudo apt update -y \
  && sudo apt install docker-ce docker-ce-cli containerd.io -y \
  && if [ ! -f /usr/local/bin/docker-compose ] ; then
        echo 'Installing Docker Compose...' \
        && COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4) \
        && sudo curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
        && sudo chmod +x /usr/local/bin/docker-compose
        else echo 'Skip Installing Docker Compose'
     fi
  sudo docker-compose -f ./Server/docker-compose.yaml pull \
  && echo 'CTC server is now running...'\
  && sudo docker-compose -f ./Server/docker-compose.yaml up -d \
  && sudo docker exec sawtooth-validator-testnet cat /etc/sawtooth/keys/validator.pub \
  && echo 'Above text is your CTC PUBLIC KEY'\
  && sudo docker exec sawtooth-validator-testnet cat /etc/sawtooth/keys/validator.priv \
  && echo 'Above text is your CTC PRIVATE KEY'\
  && read -p "Input your CTC private key : " CTC_PRIVKEY \
  && sed -i "s/<256_bit_key_secp256k1_ECDSA>/$CTC_PRIVKEY/g" ./Client/clientConfig.json \
  && sudo docker-compose -f ./Server/docker-compose.yaml down \
  && echo 'First intallation is done.'\
  && echo 'Now you need to download snapshot and setup install2.'
fi
